block.10001=short_grass grass tallgrass fern dead_bush wheat carrots potatoes beetroots \
 dandelion poppy blue_orchid allium azure_bluet red_tulip orange_tulip white_tulip pink_tulip \
 oxeye_daisy cornflower lily_of_the_valley torchflower wither_rose sweet_berry_bush \
 red_flower yellow_flower sapling oak_sapling spruce_sapling birch_sapling jungle_sapling \
 acacia_sapling dark_oak_sapling cherry_sapling pale_oak_sapling short_dry_grass bush firefly_bush

block.10002=oak_leaves spruce_leaves birch_leaves jungle_leaves acacia_leaves dark_oak_leaves \
 mangrove_leaves cherry_leaves azalea_leaves flowering_azalea_leaves pale_oak_leaves leaves leaves2 vine

block.10003=water flowing_water

block.10004=tall_grass large_fern sunflower lilac rose_bush peony double_plant tall_dry_grass

block.10005=glowstone sea_lantern torch wall_torch soul_torch soul_wall_torch \
 lantern soul_lantern shroomlight jack_o_lantern lit_pumpkin redstone_lamp:lit=true lit_redstone_lamp \
 end_rod fire soul_fire campfire:lit=true soul_campfire:lit=true beacon conduit \
 ochre_froglight verdant_froglight pearlescent_froglight glow_lichen sea_pickle respawn_anchor \
 copper_bulb:lit=true exposed_copper_bulb:lit=true weathered_copper_bulb:lit=true oxidized_copper_bulb:lit=true \
 waxed_copper_bulb:lit=true waxed_exposed_copper_bulb:lit=true waxed_weathered_copper_bulb:lit=true waxed_oxidized_copper_bulb:lit=true \
 end_portal_frame:eye=true enchanting_table

block.10006=redstone_wire redstone_block redstone_torch:lit=true redstone_wall_torch:lit=true \
 redstone_ore:lit=true deepslate_redstone_ore:lit=true repeater:powered=true comparator:powered=true \
 observer:powered=true

block.10007=nether_portal crying_obsidian amethyst_cluster large_amethyst_bud medium_amethyst_bud small_amethyst_bud \
 sculk_sensor calibrated_sculk_sensor sculk_catalyst sculk_shrieker cave_vines:berries=true cave_vines_plant:berries=true \
 creaking_heart:active=true creaking_heart:creaking_heart_state=awake trial_spawner vault

block.10008=furnace:lit=true blast_furnace:lit=true smoker:lit=true \
 candle:lit=true white_candle:lit=true orange_candle:lit=true magenta_candle:lit=true light_blue_candle:lit=true \
 yellow_candle:lit=true lime_candle:lit=true pink_candle:lit=true gray_candle:lit=true light_gray_candle:lit=true \
 cyan_candle:lit=true purple_candle:lit=true blue_candle:lit=true brown_candle:lit=true green_candle:lit=true \
 red_candle:lit=true black_candle:lit=true candle_cake:lit=true

block.10009=lava flowing_lava magma_block

block.10010=diamond_ore deepslate_diamond_ore emerald_ore deepslate_emerald_ore lapis_ore deepslate_lapis_ore \
 gold_ore deepslate_gold_ore nether_gold_ore redstone_ore:lit=false deepslate_redstone_ore:lit=false copper_ore deepslate_copper_ore \
 nether_quartz_ore ancient_debris amethyst_block budding_amethyst
