item.10005=torch soul_torch lantern soul_lantern glowstone glowstone_dust sea_lantern shroomlight jack_o_lantern \
 end_rod beacon conduit ochre_froglight verdant_froglight pearlescent_froglight glow_ink_sac glow_item_frame \
 blaze_rod blaze_powder magma_cream nether_star experience_bottle ender_eye heart_of_the_sea lava_bucket \
 copper_bulb glow_lichen sea_pickle
item.10006=redstone redstone_block redstone_torch
item.10007=amethyst_shard amethyst_cluster echo_shard glow_berries crying_obsidian sculk_catalyst sculk_sensor
item.10009=magma_block
item.10010=diamond emerald lapis_lazuli
