clouds=off

screen=[LIGHTING] [GLOW] [SHADOWS] [WATER] [CLOUDS] [SKY] [POST] [END] WAVING_PLANTS WAVE_SPEED WAVE_AMPLITUDE
screen.LIGHTING=SUN_STRENGTH MOON_STRENGTH AMBIENT_STRENGTH TORCH_STRENGTH <empty> TORCH_R TORCH_G TORCH_B
screen.GLOW=EMISSIVE_STRENGTH GLOW GLOW_STRENGTH <empty> GLOWING_ORES DYNAMIC_LIGHT
screen.SHADOWS=shadowMapResolution shadowDistance SHADOW_SOFTNESS SHADOW_DISTORT sunPathRotation
screen.WATER=WATER_REFLECTIONS WATER_CAUSTICS WATER_FOAM UNDERWATER_RAYS UNDERWATER_RAYS_STRENGTH <empty> WATER_WAVE_HEIGHT WATER_SPEED WATER_REFRACTION WATER_CLARITY WATER_R WATER_G WATER_B
screen.CLOUDS=VOLUMETRIC_CLOUDS CLOUD_STEPS CLOUD_COVERAGE CLOUD_SPEED CLOUD_HEIGHT CLOUD_THICKNESS
screen.SKY=VOLUMETRIC_LIGHT VL_STRENGTH VL_STEPS SUN_SIZE FOG_DENSITY <empty> GROUND_FOG GROUND_FOG_DENSITY GROUND_FOG_HEIGHT <empty> AURORA AURORA_STRENGTH STAR_BRIGHTNESS SUN_MOON_BRIGHTNESS <empty> CUSTOM_MOON MOON_SIZE MOON_BRIGHTNESS <empty> RAIN_OPACITY PUDDLES PUDDLE_AMOUNT
screen.POST=BLOOM BLOOM_STRENGTH EXPOSURE SATURATION CONTRAST VIGNETTE COLOR_GRADE CINEMATIC_BARS AUTO_EXPOSURE LENS_FLARE LENS_FLARE_STRENGTH
screen.END=END_STYLE <empty> BH_SIZE BH_SPIN BH_BRIGHTNESS END_NEBULA <empty> END_SMOKE END_SMOKE_DENSITY END_SMOKE_HEIGHT

sliders=shadowMapResolution shadowDistance sunPathRotation SHADOW_SOFTNESS SHADOW_DISTORT \
 SUN_STRENGTH MOON_STRENGTH AMBIENT_STRENGTH TORCH_STRENGTH EMISSIVE_STRENGTH TORCH_R TORCH_G TORCH_B \
 WAVE_SPEED WAVE_AMPLITUDE WATER_R WATER_G WATER_B WATER_CLARITY WATER_WAVE_HEIGHT WATER_SPEED WATER_REFRACTION \
 VL_STRENGTH VL_STEPS SUN_SIZE CLOUD_STEPS CLOUD_COVERAGE CLOUD_SPEED CLOUD_HEIGHT CLOUD_THICKNESS FOG_DENSITY STAR_BRIGHTNESS SUN_MOON_BRIGHTNESS BLOOM_STRENGTH EXPOSURE SATURATION CONTRAST VIGNETTE COLOR_GRADE \
 UNDERWATER_RAYS_STRENGTH GROUND_FOG_DENSITY GROUND_FOG_HEIGHT AURORA_STRENGTH LENS_FLARE_STRENGTH \
 MOON_SIZE MOON_BRIGHTNESS RAIN_OPACITY BH_SIZE BH_SPIN BH_BRIGHTNESS END_NEBULA END_SMOKE_DENSITY END_SMOKE_HEIGHT GLOW_STRENGTH PUDDLE_AMOUNT

blend.gbuffers_water.colortex1=off
